name: The Litography Project
markdown: redcarpet
pygments: true
baseurl:
host: http://thelitographyproject.com/
permalink: /:month-:day-:year/:title.html


prose:
  rooturl: '_posts'
  siteurl: 'http://thelitographyproject.com/'
  media: 'assets/images/stories'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
          placeholder: "Input Author"
          type: "text"
      - name: "cover-image"
        field:
          element: "text"
          label: "Image URL"
          value: ""
          placeholder:"assets/images/stories/NAMEOFIMAGE.JPG"
          type: "text"
      - name: "number"
        field:
          element: "number"
          label: "Story number"
          value: ""
          placeholder: "Input number of story"
          type: "number"
      - name: "location"
        field:
          element: "text"
          label: "location"
          value: ""
          placeholder: "Input location"
          type: "text"
      - name: "category"
        field:
          element: "select"
          label: "Add Categories"
          placeholder: "Choose Tags"
          options:
            - name: "Story"
              value: "story"
            - name: "Updates"
              value: "updates"
